# Generated by Django 5.1.7 on 2025-03-28 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='phone_name',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 13, 18, 53, 63530, tzinfo=datetime.timezone.utc)),
        ),
    ]
